spring:

  # JPA
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

# Log
logging:
  level:
    root: info
    org.springframework.security: debug
    org.springframework.cache: trace
    org.hibernate.orm.jdbc.bind: trace