spring:

  # JPA
  jpa:
    hibernate:
<<<<<<< HEAD
      ddl-auto: create
=======
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
>>>>>>> 8b13383 (맞팔 탐지기 일부 구현)

# Log
logging:
  level:
    root: info
    org.springframework.security: debug
    org.springframework.cache: trace
    org.hibernate.orm.jdbc.bind: trace