spring:

  # JPA
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul

# Log
logging:
  level:
    root: info
    org.springframework.security: debug
    org.springframework.cache: trace