spring:
  config:
    import:
      - infra.yml

  batch:
    job:
      enabled: false

logging:
  config: classpath:logback/logback-${spring.profiles.active:local}.xml

  level:
    org.springframework.batch.core.repository.support: DEBUG


server:
  port: 9000