spring:
  config:
    import:
      - data.yml
      - logging.yml
      - infra.yml

discord:
  webhook-uri:
    id: ${RANKING_DISCORD_WEBHOOK_ID}
    token: ${RANKING_DISCORD_WEBHOOK_TOKEN}

server:
  port: 9000