spring:
  config:
    import:
      - "aws-parameterstore:/config/moyoy-test/"

  jpa:
    hibernate:
      ddl-auto: create


aws:
  parameterstore:
    enabled: true
    prefix: /config
    name: moyoy-test